### ISSUE TITLE
SlowMo is a No No

### ISSUE THREAD

**Issue by giladyavneh** [AmirDebbie/Chat-App-Template#4]
Hey guys I had a lot of fun on this challenge.

It probably whould be better to comment out the slowMo on the pupeeter while it is headless, it takes an awfull lot of time to complete the tests that way

https://github.com/suvelocity/Chat-App-Template/blob/fc47ea446178d59281acb52cde4472f2c2f295ff/client/src/clientTest.test.js#L13

**Comment by AmirDebbie** [comment]
First of all thanks for the comment and glad to hear you enjoyed!
Unfortunately, the slowmo is necessary for the tests to run properly. If we remove it, we will need to add timeouts instead and the over all test time will remain relatively the same. 
Nevertheless, we will look in to it again.
